<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Agreement;

class AgreementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $agreements = array(
            array(
                "id" => 1,
                "name" => "MPLS Railtel",
                "agency" => "Railtel",
                "file_id" => 205,
                "type" => "Service",
                "expiry" => "2021-03-31",
                "annual_cost" => 87495419,
                "frequency" => 3,
                "paid_till" => "2020-06-01",
                "remarks" => "Invoice for July-September 2020 is under submission",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "name" => "MPLS BSNL",
                "agency" => "BSNL",
                "file_id" => 203,
                "type" => "Service",
                "expiry" => "2021-03-31",
                "annual_cost" => 10479128,
                "frequency" => 3,
                "paid_till" => "2020-03-01",
                "remarks" => "Invoice not received",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 3,
                "name" => "MPLS PGCIL",
                "agency" => "PGCIL",
                "file_id" => 198,
                "type" => "Service",
                "expiry" => "2021-03-31",
                "annual_cost" => 4512853,
                "frequency" => 3,
                "paid_till" => "2020-06-01",
                "remarks" => "Invoice for July-September 2020 is under submission",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 4,
                "name" => "Data Center Services",
                "agency" => "Railtel",
                "file_id" => 210,
                "type" => "Service",
                "expiry" => "2021-03-31",
                "annual_cost" => 10293108,
                "frequency" => 3,
                "paid_till" => "2020-03-01",
                "remarks" => "File put up for payment till June and September 2020",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 5,
                "name" => "Data Center Services e-office",
                "agency" => "Railtel",
                "file_id" => 196,
                "type" => "Service",
                "expiry" => "2021-03-31",
                "annual_cost" => 1965880,
                "frequency" => 3,
                "paid_till" => "2020-09-01",
                "remarks" => "",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 6,
                "name" => "10 Mbps ILL Connectivity- CSD",
                "agency" => "Railtel",
                "file_id" => 204,
                "type" => "Service",
                "expiry" => "2019-03-31",
                "annual_cost" => 200600,
                "frequency" => 3,
                "paid_till" => "2019-09-01",
                "remarks" => "File is under submission for ex-post-facto approval for extension till 31.03.21",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 7,
                "name" => "Outsourced Technical Manpower",
                "agency" => "Collabera",
                "file_id" => 199,
                "type" => "Service",
                "expiry" => "2020-10-31",
                "annual_cost" => 16836240,
                "frequency" => 1,
                "paid_till" => "2020-08-01",
                "remarks" => "September 2020",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 8,
                "name" => "Outsourced Manpower MTS",
                "agency" => "Virtuous",
                "file_id" => 24,
                "type" => "Service",
                "expiry" => "2020-10-31",
                "annual_cost" => 4837416,
                "frequency" => 1,
                "paid_till" => "2020-09-01",
                "remarks" => "Current period Bill not received",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 9,
                "name" => "Outsourced Manpower Security",
                "agency" => "Squad 7",
                "file_id" => 19,
                "type" => "Service",
                "expiry" => "2020-10-31",
                "annual_cost" => 2458476,
                "frequency" => 1,
                "paid_till" => "2020-09-01",
                "remarks" => "October 2020",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 10,
                "name" => "Outsourced Manpower G-NOC Operation",
                "agency" => "3i Infotech",
                "file_id" => 227,
                "type" => "Service",
                "expiry" => "2021-01-11",
                "annual_cost" => 17581207,
                "frequency" => 3,
                "paid_till" => "2020-06-01",
                "remarks" => "Septebmer 2020",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 11,
                "name" => "Oracle Annual Technical Support",
                "agency" => "Oracle",
                "file_id" => 191,
                "type" => "Service",
                "expiry" => "2020-05-31",
                "annual_cost" => 29142626,
                "frequency" => 12,
                "paid_till" => NULL,
                "remarks" => "Approval of renewal under process",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 12,
                "name" => "Oracle Advanced Customer Service",
                "agency" => "Oracle",
                "file_id" => 192,
                "type" => "Service",
                "expiry" => "2020-05-31",
                "annual_cost" => 6448089,
                "frequency" => 12,
                "paid_till" => NULL,
                "remarks" => "Approval of renewal under process",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 13,
                "name" => "PAN verification services for EPFO",
                "agency" => "UTIITSL",
                "file_id" => 67,
                "type" => "Service",
                "expiry" => "2021-08-31",
                "annual_cost" => 14160,
                "frequency" => 12,
                "paid_till" => NULL,
                "remarks" => "",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 14,
                "name" => "Redhat Product Subscription",
                "agency" => "SISIL Infotech",
                "file_id" => 194,
                "type" => "Service",
                "expiry" => "2020-11-27",
                "annual_cost" => 32208183,
                "frequency" => 12,
                "paid_till" => NULL,
                "remarks" => "Renewal for subscription under process Bids created by PDU",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 15,
                "name" => "NICSI SMS",
                "agency" => "NICSI",
                "file_id" => 115,
                "type" => "Service",
                "expiry" => NULL,
                "annual_cost" => 60000000,
                "frequency" => 3,
                "paid_till" => "2020-04-01",
                "remarks" => "Payment upto July 2020 is under process",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 16,
                "name" => "AMC of PAC",
                "agency" => "Vertiv",
                "file_id" => 88,
                "type" => "Service",
                "expiry" => "2020-12-31",
                "annual_cost" => 216223,
                "frequency" => 3,
                "paid_till" => "2019-12-01",
                "remarks" => "Signing of Agreement under process",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 17,
                "name" => "AMC of Two(2x30) KVA UPS",
                "agency" => "Vertiv",
                "file_id" => 89,
                "type" => "Service",
                "expiry" => "2020-01-31",
                "annual_cost" => 202177,
                "frequency" => 3,
                "paid_till" => "2020-04-01",
                "remarks" => "Signing Agreement is under process",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 18,
                "name" => "AMC of 2x60 KVA UPS",
                "agency" => "Vertiv",
                "file_id" => 90,
                "type" => "Service",
                "expiry" => "2020-01-31",
                "annual_cost" => 207680,
                "frequency" => 3,
                "paid_till" => "2020-01-01",
                "remarks" => "Signing Agreement is under process",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 19,
                "name" => "Storage Warranty- NICSI",
                "agency" => "NICSI",
                "file_id" => 237,
                "type" => "Service",
                "expiry" => NULL,
                "annual_cost" => 0,
                "frequency" => 0,
                "paid_till" => NULL,
                "remarks" => "Proposal under process",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 20,
                "name" => "Server Licensing",
                "agency" => "NICSI",
                "file_id" => 247,
                "type" => "Service",
                "expiry" => NULL,
                "annual_cost" => 0,
                "frequency" => 0,
                "paid_till" => NULL,
                "remarks" => "Under examination/ verficiation",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 21,
                "name" => "Network Switch ",
                "agency" => "NICSI",
                "file_id" => 243,
                "type" => "Service",
                "expiry" => NULL,
                "annual_cost" => 0,
                "frequency" => 0,
                "paid_till" => NULL,
                "remarks" => "",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 22,
                "name" => "Network Firewall",
                "agency" => "NICSI",
                "file_id" => 244,
                "type" => "Service",
                "expiry" => NULL,
                "annual_cost" => 0,
                "frequency" => 0,
                "paid_till" => NULL,
                "remarks" => "",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 23,
                "name" => "Rented Computers",
                "agency" => "United IT Services",
                "file_id" => 184,
                "type" => "Service",
                "expiry" => "2020-11-30",
                "annual_cost" => 764640,
                "frequency" => 1,
                "paid_till" => "2020-08-01",
                "remarks" => "Bill for September to November 2020 received on 6.11.2020",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 24,
                "name" => "Consultancy/maintenance services of Redhat",
                "agency" => "Integra Micro Systems Pvt Ltd",
                "file_id" => 194,
                "type" => "Service",
                "expiry" => NULL,
                "annual_cost" => 4454382,
                "frequency" => 0,
                "paid_till" => NULL,
                "remarks" => "Bids created by PDU",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 25,
                "name" => "Toll Free No. ",
                "agency" => "MTNL",
                "file_id" => 8,
                "type" => "Service",
                "expiry" => NULL,
                "annual_cost" => 1500000,
                "frequency" => 1,
                "paid_till" => "2020-08-01",
                "remarks" => "September 2020 payment is under process",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 26,
                "name" => "Electricity Bill Transit House",
                "agency" => "BSES",
                "file_id" => 61,
                "type" => "Service",
                "expiry" => NULL,
                "annual_cost" => 24000,
                "frequency" => 1,
                "paid_till" => "2020-07-01",
                "remarks" => "Current period Bill not received",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 27,
                "name" => "Gas Bill Transit House",
                "agency" => "IGL",
                "file_id" => 39,
                "type" => "Service",
                "expiry" => NULL,
                "annual_cost" => 4000,
                "frequency" => 2,
                "paid_till" => "2020-07-01",
                "remarks" => "Current period Bill not received",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 28,
                "name" => "Landline Telephones Bill",
                "agency" => "MTNL",
                "file_id" => 23,
                "type" => "Service",
                "expiry" => NULL,
                "annual_cost" => 600000,
                "frequency" => 1,
                "paid_till" => "2020-09-01",
                "remarks" => "Current period Bill not received",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 29,
                "name" => "Airtel Data Card Bill",
                "agency" => "Airtel",
                "file_id" => 9,
                "type" => "Service",
                "expiry" => NULL,
                "annual_cost" => 180000,
                "frequency" => 1,
                "paid_till" => "2020-09-01",
                "remarks" => "October 2020",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 30,
                "name" => "Washroom Hygiene",
                "agency" => "Washroom Hygiene Pvt. Ltd.",
                "file_id" => 38,
                "type" => "Service",
                "expiry" => NULL,
                "annual_cost" => 24200,
                "frequency" => 1,
                "paid_till" => "2020-08-01",
                "remarks" => "Current period Bill not received",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
        );

        Agreement::insert($agreements);
    }
}
