<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Developer;

class DeveloperSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $developers = array(
            array(
                "id" => 1,
                "name" => "VARUN VISHAL",
                "category_id" => 1,
                "status" => 1,
                "phone" => "9560026616",
                "email" => "varunvishal517@gmail.com",
                "joining_date" => "2019-11-18",
                "expertise" => "JAVA DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "B.Tech",
                "subject" => "Applied Electronics & Instrumentation",
                "education_institute" => "Gandhi institute",
                "education_location" => "Gunupur",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "name" => "AJIT RAI",
                "category_id" => 3,
                "status" => 1,
                "phone" => "7827477908",
                "email" => "ajit15.rai@gmail.com",
                "joining_date" => "2019-11-20",
                "expertise" => "JAVA DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "B.tech",
                "subject" => "ECE",
                "education_institute" => "Maharshi Markendeshwar",
                "education_location" => "??",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 3,
                "name" => "ASHUTOSH JAIN",
                "category_id" => 3,
                "status" => 1,
                "phone" => "9571202606",
                "email" => "ashutoshjain.skit@gmail.com",
                "joining_date" => "2019-11-25",
                "expertise" => "JAVA DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "B.tech",
                "subject" => "Information technology",
                "education_institute" => "Swami keshwanand SKITG/RTU",
                "education_location" => "Jaipur",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 4,
                "name" => "MATTHEW THOMAS",
                "category_id" => 3,
                "status" => 1,
                "phone" => "8130334213",
                "email" => "mathewthomas670@gmail.com",
                "joining_date" => "2019-11-29",
                "expertise" => "JAVA DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "BCA",
                "subject" => "Computer Application",
                "education_institute" => "IGNOU",
                "education_location" => "New Delhi",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 5,
                "name" => "DHARMENDRA KUMAR SHARMA",
                "category_id" => 2,
                "status" => 1,
                "phone" => "9654209285",
                "email" => "dksharma.sharma54@gmail.com",
                "joining_date" => "2019-12-02",
                "expertise" => "ANDROID APP DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => "Om Prakash Sharma",
                "mother_name" => "Vidyawati Devi",
                "hometown" => NULL,
                "qualification" => "MSC",
                "subject" => "Computer Science",
                "education_institute" => "Central University of Rajasthan",
                "education_location" => NULL,
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 6,
                "name" => "MADAN MOHAN SINGH",
                "category_id" => 2,
                "status" => 1,
                "phone" => "9760790772",
                "email" => "mohankarmkrmadan@outlook.com",
                "joining_date" => "2019-12-16",
                "expertise" => "JAVA DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "MCA",
                "subject" => "Computer Application",
                "education_institute" => "Mahatma Technical University",
                "education_location" => "Budhhanagar UP",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 7,
                "name" => "HIMANSHU DIVEDI",
                "category_id" => 3,
                "status" => 1,
                "phone" => "8410780334",
                "email" => "dwivedihimanshu54@gmail.com",
                "joining_date" => "2020-01-13",
                "expertise" => "ROBOTIC PROCESS ANALYST",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "BCA/MCA",
                "subject" => "Computer Application",
                "education_institute" => "Invertis University",
                "education_location" => "Bareily",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 8,
                "name" => "PRERIT KHARE",
                "category_id" => 1,
                "status" => 1,
                "phone" => "7838502345",
                "email" => "preritkhare@gmail.com",
                "joining_date" => "2020-03-19",
                "expertise" => "DATA ANALYST",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "MCA",
                "subject" => "Computer Application",
                "education_institute" => "Lucknow University",
                "education_location" => "Lucknow",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 9,
                "name" => "Sonam Kumari",
                "category_id" => 2,
                "status" => 1,
                "phone" => "9318327958",
                "email" => "sonamsingh0944@gmail.com",
                "joining_date" => "2020-11-11",
                "expertise" => "Java Tester",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => "Devendra Singh",
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "B.tech",
                "subject" => "CSE",
                "education_institute" => "\"Kautilya Institute",
                "education_location" => " KIT/RTU\"",
                "aadhaar" => "Jaipur",
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 10,
                "name" => "KHUSHBOO",
                "category_id" => 2,
                "status" => 1,
                "phone" => "8700794347",
                "email" => "khushbumishra112@gmail.com",
                "joining_date" => "2020-06-08",
                "expertise" => "PHP DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "B.tech",
                "subject" => "CSE",
                "education_institute" => "Maharshi Dayanand Visvidyalay",
                "education_location" => "Rohtak",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 11,
                "name" => "INDRA NARAYAN",
                "category_id" => 1,
                "status" => 1,
                "phone" => "9113115152",
                "email" => "indra.quadrasystem@gmail.com",
                "joining_date" => "2020-06-25",
                "expertise" => "PROGRAMMER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "BCA",
                "subject" => "Computer Application",
                "education_institute" => "Magadh University",
                "education_location" => "Bodh Gaya",
                "aadhaar" => NULL,
                "remark" => "Was under Sh. Md Qamar till 6th October",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 12,
                "name" => "AMIT  KUMAR DEV",
                "category_id" => 3,
                "status" => 1,
                "phone" => "7004179402",
                "email" => "mtdev5463@gmail.com",
                "joining_date" => "2020-06-30",
                "expertise" => "JAVA DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "B.tech",
                "subject" => "ECE",
                "education_institute" => "Maharshi Markendeshwar",
                "education_location" => "Ambala",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 13,
                "name" => "ANIL KUMAR",
                "category_id" => 3,
                "status" => 1,
                "phone" => "9015526986",
                "email" => "thegupta94@gmail.com",
                "joining_date" => "2020-07-23",
                "expertise" => "JAVA DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "BCA",
                "subject" => "Computer Application",
                "education_institute" => "Vivekanand Institute",
                "education_location" => "New Delhi",
                "aadhaar" => NULL,
                "remark" => "Was under Sh. S.K panda till 31-08.2020",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 14,
                "name" => "Subbareddy Arava",
                "category_id" => 2,
                "status" => 1,
                "phone" => "9848917971",
                "email" => "subbareddy.arava@gmail.com",
                "joining_date" => "2020-03-19",
                "expertise" => "PL/SQL Coder",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "B.tech",
                "subject" => "ECE",
                "education_institute" => "J. Nehru Technical university",
                "education_location" => "Anantpur",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 15,
                "name" => "PANKAJ KUMAR",
                "category_id" => 2,
                "status" => 1,
                "phone" => "8858487744",
                "email" => "csebu10@gmail.com",
                "joining_date" => "2020-09-21",
                "expertise" => "PHP DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "B.Tech",
                "subject" => "CSE",
                "education_institute" => "Bundelkhand University",
                "education_location" => "Bundelkhand",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 16,
                "name" => "PRADEEP KUMAR CHAUHAN",
                "category_id" => 1,
                "status" => 1,
                "phone" => "7531082557",
                "email" => "pradeepmca02877@gmail.com",
                "joining_date" => "2020-10-05",
                "expertise" => "JAVA DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "MCA",
                "subject" => "Computer Application",
                "education_institute" => "Rajiv Gandhi Technical University",
                "education_location" => "Bhopal",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 17,
                "name" => "ANSHU RAMAN VERMA",
                "category_id" => 2,
                "status" => 1,
                "phone" => "9690532019",
                "email" => "anshuramanverma@gmail.com",
                "joining_date" => "2020-10-12",
                "expertise" => "JAVA DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "B.Tech",
                "subject" => "ECE",
                "education_institute" => "Uttar Pradesh Pravidhik vidyalay",
                "education_location" => "Lucknow",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 18,
                "name" => "SACHIN KUMAR",
                "category_id" => 2,
                "status" => 1,
                "phone" => "8700527023",
                "email" => "sachin57249@gmail.com",
                "joining_date" => "2020-10-26",
                "expertise" => "PROGRAMMER",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => NULL,
                "subject" => NULL,
                "education_institute" => NULL,
                "education_location" => NULL,
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 19,
                "name" => "AKHILESH KUMAR",
                "category_id" => 3,
                "status" => 1,
                "phone" => "8791213571",
                "email" => "akhilesh1kd@gmail.com",
                "joining_date" => "2020-11-10",
                "expertise" => "Desktop Support Engineer",
                "reporting_id" => 1,
                "exit_date" => NULL,
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => NULL,
                "subject" => NULL,
                "education_institute" => NULL,
                "education_location" => NULL,
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 20,
                "name" => "MADHURESH KUMAR",
                "category_id" => 1,
                "status" => 0,
                "phone" => "8527080910",
                "email" => "madhureshsachan81@gmail.com",
                "joining_date" => "2019-12-04",
                "expertise" => "JAVA DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => "2020-07-31",
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => NULL,
                "subject" => NULL,
                "education_institute" => NULL,
                "education_location" => NULL,
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 21,
                "name" => "SHASHI SONE",
                "category_id" => 1,
                "status" => 0,
                "phone" => "8630481920",
                "email" => "shashisone0891@gmail.com",
                "joining_date" => "2019-12-31",
                "expertise" => "DATA ANALYST",
                "reporting_id" => 1,
                "exit_date" => "2020-07-31",
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => NULL,
                "subject" => NULL,
                "education_institute" => NULL,
                "education_location" => NULL,
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 22,
                "name" => "ALKA",
                "category_id" => 3,
                "status" => 0,
                "phone" => "7017981519",
                "email" => "alkanailwal@gmail.com",
                "joining_date" => "2020-01-07",
                "expertise" => "ROBOTIC PROCESS ANALYST",
                "reporting_id" => 1,
                "exit_date" => "2020-07-31",
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => NULL,
                "subject" => NULL,
                "education_institute" => NULL,
                "education_location" => NULL,
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 23,
                "name" => "ROHIT JANGIR",
                "category_id" => 2,
                "status" => 0,
                "phone" => "8802618529",
                "email" => "rohit.jangir.sgt@gmail.com",
                "joining_date" => "2020-01-27",
                "expertise" => "DATA ANALYST",
                "reporting_id" => 1,
                "exit_date" => "2020-07-31",
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => NULL,
                "subject" => NULL,
                "education_institute" => NULL,
                "education_location" => NULL,
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 24,
                "name" => "AMIT KUMAR",
                "category_id" => 2,
                "status" => 0,
                "phone" => "9582929275",
                "email" => "sas.amit92@gmail.com",
                "joining_date" => "2020-02-04",
                "expertise" => "DATA ANALYST",
                "reporting_id" => 1,
                "exit_date" => "2020-07-31",
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => NULL,
                "subject" => NULL,
                "education_institute" => NULL,
                "education_location" => NULL,
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 25,
                "name" => "SAWAN KUMAR SINHA",
                "category_id" => 3,
                "status" => 0,
                "phone" => "1234567890",
                "email" => "sawankumar.kumar3@gmail.com",
                "joining_date" => "2020-08-31",
                "expertise" => "Java Developer",
                "reporting_id" => 1,
                "exit_date" => "2020-05-31",
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => NULL,
                "subject" => NULL,
                "education_institute" => NULL,
                "education_location" => NULL,
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 26,
                "name" => "Pankaj Saini",
                "category_id" => 2,
                "status" => 0,
                "phone" => "8607794986",
                "email" => "pankajsaini0086@gmail.com",
                "joining_date" => "2020-08-31",
                "expertise" => "Java Developer (Struts)",
                "reporting_id" => 1,
                "exit_date" => "2020-09-07",
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => NULL,
                "subject" => NULL,
                "education_institute" => NULL,
                "education_location" => NULL,
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 27,
                "name" => "RISHIKESH",
                "category_id" => 2,
                "status" => 0,
                "phone" => "8287597034",
                "email" => "rishi.mishra070@gmail.com",
                "joining_date" => "2020-06-04",
                "expertise" => "PROGRAMMER",
                "reporting_id" => 1,
                "exit_date" => "2020-11-18",
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => NULL,
                "subject" => NULL,
                "education_institute" => NULL,
                "education_location" => NULL,
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 28,
                "name" => "Sai Raju Paila",
                "category_id" => 2,
                "status" => 0,
                "phone" => "9505965491",
                "email" => "psr.sairaj@gmail.com",
                "joining_date" => "2020-03-06",
                "expertise" => "JAVA DEVELOPER",
                "reporting_id" => 1,
                "exit_date" => "2020-12-09",
                "father_name" => NULL,
                "mother_name" => NULL,
                "hometown" => NULL,
                "qualification" => "B.Tech",
                "subject" => "ECE",
                "education_institute" => "JNTU",
                "education_location" => "Hyderbad",
                "aadhaar" => NULL,
                "remark" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
        );
        Developer::insert($developers);
    }
}
