<?php

namespace Database\Seeders;
use App\Models\Device;
use Illuminate\Database\Seeder;

class DeviceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $devices = array(
            array(
                "id" => 1,
                "oem" => "Checkpoint",
                "sublocation" => "DR-ISP-1",
                "partcode" => "15400",
                "serial" => "LR201607015167",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "oem" => "Checkpoint",
                "sublocation" => "DR-ISP-2",
                "partcode" => "15400",
                "serial" => "LR201607002745",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 3,
                "oem" => "Checkpoint",
                "sublocation" => "DR-MPLS-1",
                "partcode" => "15400",
                "serial" => "LR201607015177",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 4,
                "oem" => "Checkpoint",
                "sublocation" => "DR-MPLS-2",
                "partcode" => "15400",
                "serial" => "LR201607015127",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 5,
                "oem" => "Checkpoint ",
                "sublocation" => "DC Smart Gateway ISP-1",
                "partcode" => "15400",
                "serial" => "LR201607015995",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 6,
                "oem" => "Checkpoint ",
                "sublocation" => "DC Smart Gateway ISP-2",
                "partcode" => "15400",
                "serial" => "LR201607015934",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 7,
                "oem" => "Checkpoint ",
                "sublocation" => "DC Smart Gateway MPLS-1",
                "partcode" => "15400",
                "serial" => "LR201607015150",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 8,
                "oem" => "Checkpoint ",
                "sublocation" => "DC Smart Gateway MPLS-2",
                "partcode" => "15400",
                "serial" => "LR201607015956",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 9,
                "oem" => "Fortinet",
                "sublocation" => "FW1_DC_SF",
                "partcode" => "0",
                "serial" => "FG1K5D3I16800479",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 10,
                "oem" => "Fortinet",
                "sublocation" => "FW1_DR_SF",
                "partcode" => "0",
                "serial" => "FG1K5D3I16801857",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 11,
                "oem" => "Fortinet",
                "sublocation" => "FW1_NDC_ANALYZER",
                "partcode" => "0",
                "serial" => "FN-1KD3A16000098",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 12,
                "oem" => "Fortinet",
                "sublocation" => "FW2_DC_SF",
                "partcode" => "0",
                "serial" => "FG1K5D3I15800483",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 13,
                "oem" => "Fortinet",
                "sublocation" => "FW2_DR_SF",
                "partcode" => "0",
                "serial" => "FG1K5D3I16801903",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 14,
                "oem" => "CISCO",
                "sublocation" => "ASA ISP(CISCO) Secondry",
                "partcode" => "0",
                "serial" => "FGL181240R3",
                "location" => "NDC",
                "purchase_date" => "2014-04-25",
                "cost" => 882814,
                "support_date" => "2020-04-30",
                "amc_start" => NULL,
                "amc_end" => "2019-04-22",
                "remark" => "Passed Last date of support",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 15,
                "oem" => "CISCO",
                "sublocation" => "ASA ISP(CISCO) Primary",
                "partcode" => "0",
                "serial" => "FCH1810J5VK",
                "location" => "NDC",
                "purchase_date" => "2014-04-25",
                "cost" => 882814,
                "support_date" => "2025-09-30",
                "amc_start" => "2014-04-23",
                "amc_end" => "2019-04-22",
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 16,
                "oem" => "CISCO",
                "sublocation" => "BSNL-DR-INT-R1",
                "partcode" => "0",
                "serial" => "FXS2003Q47E",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => "2019-11-14",
                "remark" => "RMA with FXS2322Q1J2 which is covered till Sep 2021",
                "amc_cost" => 101107,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 17,
                "oem" => "CISCO",
                "sublocation" => "RAILTEL-DC-INT-R2",
                "partcode" => "0",
                "serial" => "FXS2005Q521",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => "2016-09-13",
                "amc_end" => "2021-09-12",
                "remark" => NULL,
                "amc_cost" => 101107,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 18,
                "oem" => "CISCO",
                "sublocation" => "BSNL-DC-MPLS-R1",
                "partcode" => "0",
                "serial" => "FXS2005Q1FP",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => "2016-09-13",
                "amc_end" => "2021-09-12",
                "remark" => NULL,
                "amc_cost" => 101107,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 19,
                "oem" => "CISCO",
                "sublocation" => "RAILTEL-DR-INT-R2",
                "partcode" => "0",
                "serial" => "FXS2005Q1DJ",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => "2016-09-13",
                "amc_end" => "2021-09-12",
                "remark" => NULL,
                "amc_cost" => 101107,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 20,
                "oem" => "CISCO",
                "sublocation" => "RAILTEL-DR-MPLS-R2#",
                "partcode" => "0",
                "serial" => "FXS2004Q18P",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => "2016-09-13",
                "amc_end" => "2021-09-12",
                "remark" => NULL,
                "amc_cost" => 101107,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 21,
                "oem" => "CISCO",
                "sublocation" => "PGCIL-DC-INT-R1",
                "partcode" => "0",
                "serial" => "FXS2005Q2J4",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => "2016-09-17",
                "amc_end" => "2021-09-16",
                "remark" => NULL,
                "amc_cost" => 101107,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 22,
                "oem" => "CISCO",
                "sublocation" => "RAILTEL-DC-MPLS-R2",
                "partcode" => "0",
                "serial" => "FXS2005Q463",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => "2016-09-17",
                "amc_end" => "2021-09-16",
                "remark" => NULL,
                "amc_cost" => 101107,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 23,
                "oem" => "CISCO",
                "sublocation" => "BSNL-DR-MPLS-R1",
                "partcode" => "0",
                "serial" => "FXS2005Q2J1",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => "2016-09-17",
                "amc_end" => "2021-09-16",
                "remark" => NULL,
                "amc_cost" => 101107,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 24,
                "oem" => "CISCO",
                "sublocation" => "Router",
                "partcode" => "0",
                "serial" => "ÿFOC18018864",
                "location" => "NDC",
                "purchase_date" => "2014-03-29",
                "cost" => 486686,
                "support_date" => "2022-12-31",
                "amc_start" => "2014-03-30",
                "amc_end" => "2019-03-29",
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 25,
                "oem" => "CISCO",
                "sublocation" => "Router",
                "partcode" => "0",
                "serial" => "ÿFOC18033F7H",
                "location" => "NDC",
                "purchase_date" => "2014-03-29",
                "cost" => 486686,
                "support_date" => "2022-12-31",
                "amc_start" => "2014-03-30",
                "amc_end" => "2019-03-29",
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 26,
                "oem" => "CISCO",
                "sublocation" => "Router (Faulty)",
                "partcode" => "0",
                "serial" => "FHK1317F11X",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2016-10-31",
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Passed Last date of support",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 27,
                "oem" => "CISCO",
                "sublocation" => "NDC_MPLS (CISCO)",
                "partcode" => "0",
                "serial" => "FGL191611K3",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2022-12-31",
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Under Coverage Restriction flag",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 28,
                "oem" => "CISCO",
                "sublocation" => "switch",
                "partcode" => "0",
                "serial" => "FOC20110A7T",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Incorrect Serial number",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 29,
                "oem" => "Juniper",
                "sublocation" => "Junipier_SW",
                "partcode" => "0",
                "serial" => "GD0214380046",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 30,
                "oem" => "CISCO",
                "sublocation" => "IPS 1 ",
                "partcode" => "0",
                "serial" => "JMX2029L0B0",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2024-06-30",
                "amc_start" => "2016-09-16",
                "amc_end" => "2021-09-15",
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 31,
                "oem" => "CISCO",
                "sublocation" => "IPS 2",
                "partcode" => "0",
                "serial" => "JMX2029L0AY",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2024-06-30",
                "amc_start" => "2016-09-16",
                "amc_end" => "2021-09-15",
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 32,
                "oem" => "CISCO",
                "sublocation" => "IPS 1 ",
                "partcode" => "0",
                "serial" => "JMX2029L0AS",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2024-06-30",
                "amc_start" => "2016-09-16",
                "amc_end" => "2021-09-15",
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 33,
                "oem" => "CISCO",
                "sublocation" => "IPS 2",
                "partcode" => "0",
                "serial" => "JMX2029L0AV",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2024-06-30",
                "amc_start" => "2016-09-16",
                "amc_end" => "2021-09-15",
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 34,
                "oem" => "CISCO",
                "sublocation" => " NEXUS-CORE1(FOC1803R0E4)",
                "partcode" => "0",
                "serial" => "FOC1803R0E4",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2021-10-31",
                "amc_start" => "2014-03-26",
                "amc_end" => "2019-03-29",
                "remark" => NULL,
                "amc_cost" => 67541,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 35,
                "oem" => "CISCO",
                "sublocation" => "NEXUS-Server switch",
                "partcode" => "0",
                "serial" => "FCH1810J5YZ",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2025-09-30",
                "amc_start" => "2014-04-23",
                "amc_end" => "2019-04-22",
                "remark" => "Our system is showing a different part number which is ASA5545-MB",
                "amc_cost" => 67541,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 36,
                "oem" => "CISCO",
                "sublocation" => "DC-NEXUS-CORE-SW1#",
                "partcode" => "0",
                "serial" => "JPG2024002M",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => "2016-09-13",
                "amc_end" => "2021-09-12",
                "remark" => NULL,
                "amc_cost" => 1372324,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 37,
                "oem" => "CISCO",
                "sublocation" => "DC-NEXUS-CORE-SW2#",
                "partcode" => "0",
                "serial" => "JAF1750BCLJ",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => "2016-09-13",
                "amc_end" => "2021-09-12",
                "remark" => NULL,
                "amc_cost" => 1372324,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 38,
                "oem" => "CISCO",
                "sublocation" => "C9372TXSwitch",
                "partcode" => "0",
                "serial" => "FDO2132125Z",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2023-10-31",
                "amc_start" => "2017-12-24",
                "amc_end" => "2022-12-23",
                "remark" => NULL,
                "amc_cost" => 100292,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 39,
                "oem" => "CISCO",
                "sublocation" => "HEART-BEAT-SWITCH",
                "partcode" => "0",
                "serial" => "FDO213217JM",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2023-10-31",
                "amc_start" => "2017-12-24",
                "amc_end" => "2022-12-23",
                "remark" => NULL,
                "amc_cost" => 100292,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 40,
                "oem" => "CISCO",
                "sublocation" => "DR-NEXUS-CORE-SW2#",
                "partcode" => "0",
                "serial" => "JPG2025002V",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => "2016-09-05",
                "remark" => "RMA with JAF1750BCLJ which is covered till Sep 2021",
                "amc_cost" => 1372324,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 41,
                "oem" => "CISCO",
                "sublocation" => "DR-NEXUS-CORE-SW1#",
                "partcode" => "0",
                "serial" => "JPG2024002M",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => "2016-09-13",
                "amc_end" => "2021-09-12",
                "remark" => NULL,
                "amc_cost" => 1372324,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 42,
                "oem" => "Checkpoint",
                "sublocation" => " DR Management Server  ",
                "partcode" => "0",
                "serial" => "LR201606013949",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 43,
                "oem" => "Checkpoint ",
                "sublocation" => "DC Smart Management Server  ",
                "partcode" => "0",
                "serial" => "LR201606013955",
                "location" => NULL,
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 44,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch_13(CISCO)",
                "partcode" => "0",
                "serial" => "FOC0802W0ZL",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2011-12-31",
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Passed Last date of support",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 45,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch_14(CISCO)",
                "partcode" => "0",
                "serial" => "FOC0808Z1KX",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2011-12-31",
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Passed Last date of support",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 46,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch",
                "partcode" => "0",
                "serial" => "0",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Serial number is missing",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 47,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch_12(CISCO)",
                "partcode" => "0",
                "serial" => "FCQ1606Y3WJ",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2019-10-31",
                "amc_start" => NULL,
                "amc_end" => "2017-03-28",
                "remark" => NULL,
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 48,
                "oem" => "CISCO",
                "sublocation" => "Switch",
                "partcode" => "0",
                "serial" => "FOC144146K3",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Incorrect Serial number",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 49,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch_6(CISCO)",
                "partcode" => "0",
                "serial" => "FCQ1606Y3YN",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2019-10-31",
                "amc_start" => NULL,
                "amc_end" => "2017-03-28",
                "remark" => "Passed Last date of support",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 50,
                "oem" => "CISCO",
                "sublocation" => "GNOC_SW_10",
                "partcode" => "0",
                "serial" => "FCQ1606Y3YZ",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2019-10-31",
                "amc_start" => NULL,
                "amc_end" => "2017-03-28",
                "remark" => "Passed Last date of support",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 51,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch",
                "partcode" => "0",
                "serial" => "0",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Serial number is missing",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 52,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch_5(CISCO)",
                "partcode" => "0",
                "serial" => "FOC1351Y4JH",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2019-10-31",
                "amc_start" => NULL,
                "amc_end" => "2013-01-22",
                "remark" => "Passed Last date of support",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 53,
                "oem" => "CISCO",
                "sublocation" => "L2_MPLS_10(CISCO)",
                "partcode" => "0",
                "serial" => "FCQ1606Y3YZ",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2019-10-31",
                "amc_start" => NULL,
                "amc_end" => "2017-03-28",
                "remark" => "Passed Last date of support",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 54,
                "oem" => "CISCO",
                "sublocation" => "MPLS-S2(CISCO)",
                "partcode" => "0",
                "serial" => "FOC1605X0NX",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2020-11-30",
                "amc_start" => "2012-04-02",
                "amc_end" => "2017-04-02",
                "remark" => "Passed Last date of support",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 55,
                "oem" => "CISCO",
                "sublocation" => "Mpls_ Switch(CISCO)",
                "partcode" => "0",
                "serial" => "FOC1741W1P2",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2020-11-30",
                "amc_start" => NULL,
                "amc_end" => "2018-12-11",
                "remark" => "Passed Last date of support",
                "amc_cost" => 13561,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 56,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch",
                "partcode" => "0",
                "serial" => "0",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Serial number is missing",
                "amc_cost" => 13561,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 57,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch_16(CISCO)",
                "partcode" => "0",
                "serial" => "FOC1741W1U6",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2020-11-30",
                "amc_start" => NULL,
                "amc_end" => "2018-12-11",
                "remark" => "Passed Last date of support",
                "amc_cost" => 13561,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 58,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch_15(CISCO)",
                "partcode" => "0",
                "serial" => "FOC1741V1RG",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2020-11-30",
                "amc_start" => NULL,
                "amc_end" => "2018-12-11",
                "remark" => "Passed Last date of support",
                "amc_cost" => 13561,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 59,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch_9(CISCO)",
                "partcode" => "0",
                "serial" => "FOC1807Z2AQ",
                "location" => "NDC",
                "purchase_date" => "2014-03-31",
                "cost" => 62471,
                "support_date" => "2026-10-31",
                "amc_start" => "2014-03-30",
                "amc_end" => "2019-03-25",
                "remark" => NULL,
                "amc_cost" => 13561,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 60,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch_8(CISCO)",
                "partcode" => "0",
                "serial" => "FOC1807Z2EL",
                "location" => "NDC",
                "purchase_date" => "2014-03-31",
                "cost" => 62471,
                "support_date" => "2026-10-31",
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => NULL,
                "amc_cost" => 13561,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 61,
                "oem" => "CISCO",
                "sublocation" => "DB-MGMT-SW#",
                "partcode" => "0",
                "serial" => "FCW2034B0VY",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2026-10-31",
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Never Covered",
                "amc_cost" => 13561,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 62,
                "oem" => "CISCO",
                "sublocation" => "Network-MGMT-SW#",
                "partcode" => "0",
                "serial" => "FOC2012Z05D",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => 93852,
                "support_date" => "2026-10-31",
                "amc_start" => "2016-10-21",
                "amc_end" => "2017-10-20",
                "remark" => "Under Coverage Restriction flag",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 63,
                "oem" => "CISCO",
                "sublocation" => "L2_Switch",
                "partcode" => "0",
                "serial" => "0",
                "location" => "NDC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => NULL,
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Serial number is missing",
                "amc_cost" => 21114,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 64,
                "oem" => "CISCO",
                "sublocation" => "DC-INT-SW1#",
                "partcode" => "0",
                "serial" => "FDO2028Q05Z",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2026-10-31",
                "amc_start" => "2016-09-12",
                "amc_end" => "2021-09-11",
                "remark" => NULL,
                "amc_cost" => 59051,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 65,
                "oem" => "CISCO",
                "sublocation" => "DC-INT-SW2#",
                "partcode" => "0",
                "serial" => "FDO2028Q05N",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2026-10-31",
                "amc_start" => "2016-09-12",
                "amc_end" => "2021-09-11",
                "remark" => NULL,
                "amc_cost" => 59051,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 66,
                "oem" => "CISCO",
                "sublocation" => "DC-MPLS-SW1",
                "partcode" => "0",
                "serial" => "FDO2028E0BK",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2026-10-31",
                "amc_start" => "2016-09-12",
                "amc_end" => "2021-09-11",
                "remark" => NULL,
                "amc_cost" => 59051,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 67,
                "oem" => "CISCO",
                "sublocation" => "DC-MPLS-SW2",
                "partcode" => "0",
                "serial" => "FDO2028E0BL",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2026-10-31",
                "amc_start" => "2016-09-12",
                "amc_end" => "2021-09-11",
                "remark" => NULL,
                "amc_cost" => 59051,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 68,
                "oem" => "CISCO",
                "sublocation" => "DR-INT-SW1#",
                "partcode" => "0",
                "serial" => "FDO2028E0BH",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2026-10-31",
                "amc_start" => "2016-09-12",
                "amc_end" => "2021-09-11",
                "remark" => NULL,
                "amc_cost" => 59051,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 69,
                "oem" => "CISCO",
                "sublocation" => "DR-INT-SW2#",
                "partcode" => "0",
                "serial" => "FDO2028E0BE",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2026-10-31",
                "amc_start" => "2016-09-12",
                "amc_end" => "2021-09-11",
                "remark" => NULL,
                "amc_cost" => 59051,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 70,
                "oem" => "CISCO",
                "sublocation" => "DR-MPLS-SW1#",
                "partcode" => "0",
                "serial" => "FDO2028E0BD",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2026-10-31",
                "amc_start" => "2016-09-12",
                "amc_end" => "2021-09-11",
                "remark" => NULL,
                "amc_cost" => 59051,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 71,
                "oem" => "CISCO",
                "sublocation" => "DR-MPLS-SW2#",
                "partcode" => "0",
                "serial" => "FDO2028E0BF",
                "location" => "DR",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2026-10-31",
                "amc_start" => "2016-09-12",
                "amc_end" => "2021-09-11",
                "remark" => NULL,
                "amc_cost" => 59051,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 72,
                "oem" => "CISCO",
                "sublocation" => "Main -LAN -Switch(CISCO)",
                "partcode" => "0",
                "serial" => "FDO1807Q098",
                "location" => "NDC",
                "purchase_date" => "2014-03-31",
                "cost" => 143462,
                "support_date" => "2026-10-31",
                "amc_start" => "2014-03-26",
                "amc_end" => "2019-03-25",
                "remark" => NULL,
                "amc_cost" => 21114,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 73,
                "oem" => "CISCO",
                "sublocation" => "EPFO_INT_SW1(CISCO)",
                "partcode" => "0",
                "serial" => "FDO1807Q09L",
                "location" => "NDC",
                "purchase_date" => "2014-03-31",
                "cost" => 143462,
                "support_date" => "2026-10-31",
                "amc_start" => "2014-03-26",
                "amc_end" => "2019-03-25",
                "remark" => NULL,
                "amc_cost" => 21114,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 74,
                "oem" => "CISCO",
                "sublocation" => "switch",
                "partcode" => "0",
                "serial" => "FDO1807Q09M",
                "location" => "NDC",
                "purchase_date" => "2014-03-31",
                "cost" => 143462,
                "support_date" => "2026-10-31",
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Under Coverage Restriction flag",
                "amc_cost" => 21114,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 75,
                "oem" => "CISCO",
                "sublocation" => "DATA-MGMT-SW#",
                "partcode" => "0",
                "serial" => "FDO1934E0XD",
                "location" => "DC",
                "purchase_date" => NULL,
                "cost" => NULL,
                "support_date" => "2026-10-31",
                "amc_start" => NULL,
                "amc_end" => NULL,
                "remark" => "Under Coverage Restriction flag",
                "amc_cost" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
        );
        Device::insert($devices);
    }
}
