<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Official;

class OfficialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $officials = array(
            array(
                "id" => 1,
                "name" => "Pankaj Raman",
                "title" => "Shri",
                "designation" => "ACC",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "name" => "Sanjay Kesari",
                "title" => "Shri",
                "designation" => "RPFC",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 3,
                "name" => "K Rupeshor Singh",
                "title" => "Shri",
                "designation" => "RPFC",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 4,
                "name" => "Yogesh Kumar",
                "title" => "Shri",
                "designation" => "RPFC",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 5,
                "name" => "Gaurav Meena",
                "title" => "Shri",
                "designation" => "APFC",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 6,
                "name" => "Narender Singh Rawat",
                "title" => "Shri",
                "designation" => "SO",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 7,
                "name" => "NARENDRA MESHARAM",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 8,
                "name" => "S.K.PATTANAIK",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 9,
                "name" => "MOHAMMAD QAMAR",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 10,
                "name" => "Harsh Vardhan Kaushik",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 11,
                "name" => "SHANTI SIVARAM",
                "title" => "Mrs",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 12,
                "name" => "SATHYABAMA",
                "title" => "Mrs",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 13,
                "name" => "S.K. PANDA",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 14,
                "name" => "D.K. DHARNI",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 15,
                "name" => "V. CHANDRASEKARAN",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 16,
                "name" => "K. SUNDARA RAMAN",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 17,
                "name" => "R. SURESH KUMAR",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 18,
                "name" => "S. BASKARAN",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 19,
                "name" => "Jose Martin",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 20,
                "name" => "MANOJ RS",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 21,
                "name" => "H Gowda",
                "title" => "Shri",
                "designation" => "DD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 22,
                "name" => "NV BAIJU",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 23,
                "name" => "NHVN CHANDRA SEKHAR",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 24,
                "name" => "SMITA SONI",
                "title" => "Mrs",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 25,
                "name" => "PRASHANT KUMAR",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 26,
                "name" => "LEENA AGARWAL",
                "title" => "Mrs",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 27,
                "name" => "SUMIT PRAKASH",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 28,
                "name" => "AJAY AGGARWAL",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 29,
                "name" => "VIKRAM DATTATRI",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 30,
                "name" => "Kapil Verma",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 31,
                "name" => "DIVYA ARORA",
                "title" => "Ms.",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 32,
                "name" => "SAURABH BAJPAI",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 33,
                "name" => "ANIL KUMAR",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 34,
                "name" => "RAHUL TANWAR",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 35,
                "name" => "Hari Kiran",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 36,
                "name" => "Arun Kumar",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 37,
                "name" => "VIPIN GUPTA",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 38,
                "name" => "Arvind dhar DWIVEDI",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 39,
                "name" => "Sanjay Kunjam",
                "title" => "Shri",
                "designation" => "AD",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 40,
                "name" => "BENNY THOMAS",
                "title" => "Shri",
                "designation" => "DPA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 41,
                "name" => "VINAY SAINI",
                "title" => "Shri",
                "designation" => "DPA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 42,
                "name" => "YOGESH KUMAR",
                "title" => "Shri",
                "designation" => "DPA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 43,
                "name" => "RAJ KUMAR PRASAD",
                "title" => "Shri",
                "designation" => "DPA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 44,
                "name" => "PRINCE",
                "title" => "Shri",
                "designation" => "DPA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 45,
                "name" => "BRK DURGA",
                "title" => "Mrs",
                "designation" => "DPA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 46,
                "name" => "AMIT CHAUHAN",
                "title" => "Shri",
                "designation" => "DPA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 47,
                "name" => "SANJAY KUMAR",
                "title" => "Shri",
                "designation" => "DPA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 48,
                "name" => "SHYAM KR.KASHYAP",
                "title" => "Shri",
                "designation" => "DPA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 49,
                "name" => "JAGMOHAN PAL",
                "title" => "Shri",
                "designation" => "DPA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 50,
                "name" => "MOHIT PRAKASH",
                "title" => "Shri",
                "designation" => "DPA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 51,
                "name" => "Rakesh Dabas",
                "title" => "Shri",
                "designation" => "PA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 52,
                "name" => "Laxman",
                "title" => "Shri",
                "designation" => "MTA",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 53,
                "name" => "Satish",
                "title" => "Shri",
                "designation" => "Driver",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 54,
                "name" => "Other",
                "title" => "Shri",
                "designation" => "Other",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
        );
        Official::insert($officials);
    }
}
