<div class="grid gap-5 md:grid-cols-2">
    <div class="form-group"><label for="name">Name</label><input id="name" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name', $developer->name ?? '') }}" required>@error('name')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div class="form-group"><label for="status">Status</label><select id="status" class="form-control" name="status">@foreach(['active' => 'Active', 'discontinued' => 'Discontinued'] as $value => $label)<option value="{{ $value }}" @selected(old('status', $developer->status ?? 'active') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div class="form-group"><label for="category_id">Category</label><select id="category_id" class="form-control" name="category_id"><option value="">Uncategorized</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $developer->category_id ?? '') == $category->id)>{{ $category->name }}</option>@endforeach</select></div>
    <div class="form-group"><label for="reporting_id">Reports to</label><select id="reporting_id" class="form-control" name="reporting_id"><option value="">Unassigned</option>@foreach($managers as $manager)<option value="{{ $manager->id }}" @selected(old('reporting_id', $developer->reporting_id ?? '') == $manager->id)>{{ $manager->name }}</option>@endforeach</select></div>
    <div class="form-group"><label for="email">Email</label><input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email', $developer->email ?? '') }}">@error('email')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div class="form-group"><label for="phone">Phone</label><input id="phone" class="form-control" name="phone" value="{{ old('phone', $developer->phone ?? '') }}"></div>
    <div class="form-group"><label for="salary">Salary</label><input id="salary" class="form-control" name="salary" value="{{ old('salary', $developer->salary ?? '') }}"></div>
    <div class="form-group md:col-span-2"><label for="remarks">Remarks</label><textarea id="remarks" class="form-control" name="remarks" rows="4">{{ old('remarks', $developer->remarks ?? '') }}</textarea></div>
</div>
