<div class="grid gap-5 md:grid-cols-2">
    <div class="form-group md:col-span-2"><label for="title">Title</label><input id="title" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title', $task->title ?? '') }}" required>@error('title')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
    <div class="form-group md:col-span-2"><label for="description">Description</label><textarea id="description" class="form-control" name="description" rows="4">{{ old('description', $task->description ?? '') }}</textarea></div>
    <div class="form-group"><label for="assigned_to">Assignee</label><select id="assigned_to" class="form-control" name="assigned_to"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('assigned_to', $task->assigned_to ?? '') == $user->id)>{{ $user->name }}</option>@endforeach</select></div>
    <div class="form-group"><label for="file_id">File record</label><select id="file_id" class="form-control" name="file_id"><option value="">No file</option>@foreach($files as $file)<option value="{{ $file->id }}" @selected(old('file_id', $task->file_id ?? '') == $file->id)>{{ $file->name }}</option>@endforeach</select></div>
    <div class="form-group"><label for="priority">Priority</label><select id="priority" class="form-control" name="priority">@foreach(['low','normal','high','urgent'] as $value)<option value="{{ $value }}" @selected(old('priority', $task->priority ?? 'normal') === $value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
    <div class="form-group"><label for="status">Status</label><select id="status" class="form-control" name="status">@foreach(['pending','in_progress','completed','cancelled'] as $value)<option value="{{ $value }}" @selected(old('status', $task->status ?? 'pending') === $value)>{{ ucfirst(str_replace('_', ' ', $value)) }}</option>@endforeach</select></div>
    <div class="form-group"><label for="due_date">Due date</label><input id="due_date" type="date" class="form-control" name="due_date" value="{{ old('due_date', isset($task) && $task->due_date ? $task->due_date->format('Y-m-d') : '') }}"></div>
    <div class="form-group md:col-span-2"><label for="remarks">Remarks</label><textarea id="remarks" class="form-control" name="remarks" rows="3">{{ old('remarks', $task->remarks ?? '') }}</textarea></div>
</div>
